# Generated by Django 5.0.6 on 2024-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_total_value_portfolio_crypto_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='crypto_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
